name: Generate Repo Descriptions

on:
  push:
    branches:
      - '*'  # Trigger on push to any branch of any repository

jobs:
  generate_descriptions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests google-generativeai

      - name: Generate descriptions
        run: |
          python main.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update repo descriptions"
          file_pattern: projects.json
